# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rtsp_stream_pb2 as rtsp__stream__pb2


class RtspstreamStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStreaming = channel.unary_unary(
        '/rtspstream.Rtspstream/GetStreaming',
        request_serializer=rtsp__stream__pb2.AuthToken.SerializeToString,
        response_deserializer=rtsp__stream__pb2.StreamData.FromString,
        )
    self.GetCheckStreaming = channel.unary_unary(
        '/rtspstream.Rtspstream/GetCheckStreaming',
        request_serializer=rtsp__stream__pb2.AuthToken.SerializeToString,
        response_deserializer=rtsp__stream__pb2.CheckData.FromString,
        )


class RtspstreamServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStreaming(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCheckStreaming(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RtspstreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStreaming': grpc.unary_unary_rpc_method_handler(
          servicer.GetStreaming,
          request_deserializer=rtsp__stream__pb2.AuthToken.FromString,
          response_serializer=rtsp__stream__pb2.StreamData.SerializeToString,
      ),
      'GetCheckStreaming': grpc.unary_unary_rpc_method_handler(
          servicer.GetCheckStreaming,
          request_deserializer=rtsp__stream__pb2.AuthToken.FromString,
          response_serializer=rtsp__stream__pb2.CheckData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rtspstream.Rtspstream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
