# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtsp_stream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rtsp_stream.proto',
  package='rtspstream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11rtsp_stream.proto\x12\nrtspstream\"T\n\tAuthToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x12\n\nimageWidth\x18\x03 \x01(\x05\x12\x13\n\x0bimageHeight\x18\x04 \x01(\x05\"\x1f\n\tCheckData\x12\x12\n\nreadyCheck\x18\x01 \x01(\x05\"P\n\nStreamData\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x13\n\x0b\x63\x61rDetected\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x32\x92\x01\n\nRtspstream\x12?\n\x0cGetStreaming\x12\x15.rtspstream.AuthToken\x1a\x16.rtspstream.StreamData\"\x00\x12\x43\n\x11GetCheckStreaming\x12\x15.rtspstream.AuthToken\x1a\x15.rtspstream.CheckData\"\x00\x62\x06proto3')
)




_AUTHTOKEN = _descriptor.Descriptor(
  name='AuthToken',
  full_name='rtspstream.AuthToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='rtspstream.AuthToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='rtspstream.AuthToken.channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageWidth', full_name='rtspstream.AuthToken.imageWidth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageHeight', full_name='rtspstream.AuthToken.imageHeight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=117,
)


_CHECKDATA = _descriptor.Descriptor(
  name='CheckData',
  full_name='rtspstream.CheckData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readyCheck', full_name='rtspstream.CheckData.readyCheck', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=150,
)


_STREAMDATA = _descriptor.Descriptor(
  name='StreamData',
  full_name='rtspstream.StreamData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='rtspstream.StreamData.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='rtspstream.StreamData.channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carDetected', full_name='rtspstream.StreamData.carDetected', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='rtspstream.StreamData.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=232,
)

DESCRIPTOR.message_types_by_name['AuthToken'] = _AUTHTOKEN
DESCRIPTOR.message_types_by_name['CheckData'] = _CHECKDATA
DESCRIPTOR.message_types_by_name['StreamData'] = _STREAMDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthToken = _reflection.GeneratedProtocolMessageType('AuthToken', (_message.Message,), dict(
  DESCRIPTOR = _AUTHTOKEN,
  __module__ = 'rtsp_stream_pb2'
  # @@protoc_insertion_point(class_scope:rtspstream.AuthToken)
  ))
_sym_db.RegisterMessage(AuthToken)

CheckData = _reflection.GeneratedProtocolMessageType('CheckData', (_message.Message,), dict(
  DESCRIPTOR = _CHECKDATA,
  __module__ = 'rtsp_stream_pb2'
  # @@protoc_insertion_point(class_scope:rtspstream.CheckData)
  ))
_sym_db.RegisterMessage(CheckData)

StreamData = _reflection.GeneratedProtocolMessageType('StreamData', (_message.Message,), dict(
  DESCRIPTOR = _STREAMDATA,
  __module__ = 'rtsp_stream_pb2'
  # @@protoc_insertion_point(class_scope:rtspstream.StreamData)
  ))
_sym_db.RegisterMessage(StreamData)



_RTSPSTREAM = _descriptor.ServiceDescriptor(
  name='Rtspstream',
  full_name='rtspstream.Rtspstream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=235,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStreaming',
    full_name='rtspstream.Rtspstream.GetStreaming',
    index=0,
    containing_service=None,
    input_type=_AUTHTOKEN,
    output_type=_STREAMDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCheckStreaming',
    full_name='rtspstream.Rtspstream.GetCheckStreaming',
    index=1,
    containing_service=None,
    input_type=_AUTHTOKEN,
    output_type=_CHECKDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RTSPSTREAM)

DESCRIPTOR.services_by_name['Rtspstream'] = _RTSPSTREAM

# @@protoc_insertion_point(module_scope)
